# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

require 'google/bigquery/property/array'
require 'google/bigquery/property/base'

module Google
  module Bigquery
    module Data
      # A class to manage data for Fields for table.
      class TableFields
        include Comparable

        attr_reader :description
        attr_reader :fields
        attr_reader :mode
        attr_reader :name
        attr_reader :type

        def to_json(_arg = nil)
          {
            'description' => description,
            'fields' => fields,
            'mode' => mode,
            'name' => name,
            'type' => type
          }.reject { |_k, v| v.nil? }.to_json
        end

        def to_s
          {
            description: description,
            fields: fields,
            mode: mode,
            name: name,
            type: type
          }.reject { |_k, v| v.nil? }.map { |k, v| "#{k}: #{v}" }.join(', ')
        end

        def ==(other)
          return false unless other.is_a? TableFields
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            return false if compare[:self] != compare[:other]
          end
          true
        end

        def <=>(other)
          return false unless other.is_a? TableFields
          compare_fields(other).each do |compare|
            next if compare[:self].nil? || compare[:other].nil?
            result = compare[:self] <=> compare[:other]
            return result unless result.zero?
          end
          0
        end

        private

        def compare_fields(other)
          [
            { self: description, other: other.description },
            { self: fields, other: other.fields },
            { self: mode, other: other.mode },
            { self: name, other: other.name },
            { self: type, other: other.type }
          ]
        end
      end

      # Manages a TableFields nested object
      # Data is coming from the GCP API
      class TableFieldsApi < TableFields
        def initialize(args)
          @description = Google::Bigquery::Property::String.api_munge(args['description'])
          @fields = Google::Bigquery::Property::StringArray.api_munge(args['fields'])
          @mode = Google::Bigquery::Property::Enum.api_munge(args['mode'])
          @name = Google::Bigquery::Property::String.api_munge(args['name'])
          @type = Google::Bigquery::Property::Enum.api_munge(args['type'])
        end
      end

      # Manages a TableFields nested object
      # Data is coming from the Puppet manifest
      class TableFieldsCatalog < TableFields
        def initialize(args)
          @description = Google::Bigquery::Property::String.unsafe_munge(args['description'])
          @fields = Google::Bigquery::Property::StringArray.unsafe_munge(args['fields'])
          @mode = Google::Bigquery::Property::Enum.unsafe_munge(args['mode'])
          @name = Google::Bigquery::Property::String.unsafe_munge(args['name'])
          @type = Google::Bigquery::Property::Enum.unsafe_munge(args['type'])
        end
      end
    end

    module Property
      # A class to manage input to Fields for table.
      class TableFields < Google::Bigquery::Property::Base
        # Used for parsing Puppet catalog
        def unsafe_munge(value)
          self.class.unsafe_munge(value)
        end

        # Used for parsing Puppet catalog
        def self.unsafe_munge(value)
          return if value.nil?
          Data::TableFieldsCatalog.new(value)
        end

        # Used for parsing GCP API responses
        def self.api_munge(value)
          return if value.nil?
          Data::TableFieldsApi.new(value)
        end
      end

      # A Puppet property that holds an integer
      class TableFieldsArray < Google::Bigquery::Property::Array
        # Used for parsing Puppet catalog
        def unsafe_munge(value)
          self.class.unsafe_munge(value)
        end

        # Used for parsing Puppet catalog
        def self.unsafe_munge(value)
          return if value.nil?
          return TableFields.unsafe_munge(value) \
            unless value.is_a?(::Array)
          value.map { |v| TableFields.unsafe_munge(v) }
        end

        # Used for parsing GCP API responses
        def self.api_munge(value)
          return if value.nil?
          return TableFields.api_munge(value) \
            unless value.is_a?(::Array)
          value.map { |v| TableFields.api_munge(v) }
        end
      end
    end
  end
end
