# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

require 'google/bigquery/property/boolean'
require 'google/bigquery/property/enum'
require 'google/bigquery/property/integer'
require 'google/bigquery/property/namevalues'
require 'google/bigquery/property/string'
require 'google/bigquery/property/string_array'
require 'google/bigquery/property/table_bigtable_options'
require 'google/bigquery/property/table_column_families'
require 'google/bigquery/property/table_columns'
require 'google/bigquery/property/table_csv_options'
require 'google/bigquery/property/table_encryption_configuration'
require 'google/bigquery/property/table_external_data_configuration'
require 'google/bigquery/property/table_fields'
require 'google/bigquery/property/table_google_sheets_options'
require 'google/bigquery/property/table_schema'
require 'google/bigquery/property/table_streaming_buffer'
require 'google/bigquery/property/table_table_reference'
require 'google/bigquery/property/table_time_partitioning'
require 'google/bigquery/property/table_user_defined_function_resources'
require 'google/bigquery/property/table_view'
require 'puppet'

Puppet::Type.newtype(:gbigquery_table) do
  @doc = 'A Table that belongs to a Dataset'

  autorequire(:gauth_credential) do
    credential = self[:credential]
    raise "#{ref}: required property 'credential' is missing" if credential.nil?
    [credential]
  end

  ensurable

  newparam :credential do
    desc <<-DESC
      A gauth_credential name to be used to authenticate with Google Cloud
      Platform.
    DESC
  end

  newparam(:project) do
    desc 'A Google Cloud Platform project to manage.'
  end

  newparam(:name, namevar: true) do
    # TODO(nelsona): Make this description to match the key of the object.
    desc 'The name of the Table.'
  end

  newparam(:dataset, parent: Google::Bigquery::Property::String) do
    desc 'Name of the dataset'
  end

  newproperty(:table_reference, parent: Google::Bigquery::Property::TableTableReference) do
    desc 'Reference describing the ID of this table'
  end

  newproperty(:creation_time, parent: Google::Bigquery::Property::Integer) do
    desc 'The time when this dataset was created, in milliseconds since the epoch. (output only)'
  end

  newproperty(:description, parent: Google::Bigquery::Property::String) do
    desc 'A user-friendly description of the dataset'
  end

  newproperty(:friendly_name, parent: Google::Bigquery::Property::String) do
    desc 'A descriptive name for this table'
  end

  newproperty(:id, parent: Google::Bigquery::Property::String) do
    desc 'An opaque ID uniquely identifying the table. (output only)'
  end

  newproperty(:labels, parent: Google::Bigquery::Property::NameValues) do
    desc <<-DOC
      The labels associated with this dataset. You can use these to organize and group your
      datasets
    DOC
  end

  newproperty(:last_modified_time, parent: Google::Bigquery::Property::Integer) do
    desc <<-DOC
      The time when this table was last modified, in milliseconds since the epoch. (output only)
    DOC
  end

  newproperty(:location, parent: Google::Bigquery::Property::String) do
    desc <<-DOC
      The geographic location where the table resides. This value is inherited from the dataset.
      (output only)
    DOC
  end

  newproperty(:num_bytes, parent: Google::Bigquery::Property::Integer) do
    desc <<-DOC
      The size of this table in bytes, excluding any data in the streaming buffer. (output only)
    DOC
  end

  newproperty(:num_long_term_bytes, parent: Google::Bigquery::Property::Integer) do
    desc 'The number of bytes in the table that are considered "long-term storage". (output only)'
  end

  newproperty(:num_rows, parent: Google::Bigquery::Property::Integer) do
    desc <<-DOC
      The number of rows of data in this table, excluding any data in the streaming buffer. (output
      only)
    DOC
  end

  newproperty(:type, parent: Google::Bigquery::Property::Enum) do
    desc 'Describes the table type (output only)'
    newvalue(:TABLE)
    newvalue(:VIEW)
    newvalue(:EXTERNAL)
  end

  newproperty(:view, parent: Google::Bigquery::Property::TableView) do
    desc 'The view definition.'
  end

  newproperty(:time_partitioning, parent: Google::Bigquery::Property::TableTimePartitioning) do
    desc 'If specified, configures time-based partitioning for this table.'
  end

  newproperty(:streaming_buffer, parent: Google::Bigquery::Property::TableStreamingBuffer) do
    desc <<-DOC
      Contains information regarding this table's streaming buffer, if one is present. This field
      will be absent if the table is not being streamed to or if there is no data in the streaming
      buffer. (output only)
    DOC
  end

  newproperty(:schema, parent: Google::Bigquery::Property::TableSchema) do
    desc 'Describes the schema of this table'
  end

  newproperty(:encryption_configuration,
              parent: Google::Bigquery::Property::TableEncryptionConfiguration) do
    desc 'Custom encryption configuration'
  end

  newproperty(:expiration_time, parent: Google::Bigquery::Property::Integer) do
    desc <<-DOC
      The time when this table expires, in milliseconds since the epoch. If not present, the table
      will persist indefinitely.
    DOC
  end

  newproperty(:external_data_configuration,
              parent: Google::Bigquery::Property::TableExternalDataConfiguration) do
    desc <<-DOC
      Describes the data format, location, and other properties of a table stored outside of
      BigQuery. By defining these properties, the data source can then be queried as if it were a
      standard BigQuery table.
    DOC
  end
end
